version: '3.7'
services:
    nginx:
        image: nginx:latest
        depends_on:
            - client
            - server
            - mongo
        volumes:
            - type: bind
              source: ./nginx.conf
              target: /etc/nginx/nginx.conf
        ports:
            - target: 80
              protocol: tcp
              published: 80
        networks:
            - myapp
    server:
        build:
            context: ./server
        ports:
            - target: 8080
              protocol: tcp
              published: 8080
        depends_on:
            - mongo
        networks:
            - myapp
    client:
        build:
            context: ./client
        expose:
            - '3000'
        depends_on:
            - server
            - mongo
        environment:
            - REACT_APP_SERVICE_HOST=${REACT_APP_SERVICE_HOST}
        networks:
            - myapp
    mongo:
        image: mongo:latest
        expose:
            - '27017'
        networks:
            - myapp
    mongo-seed:
        image: fvilers/mongo-seed:1.0.0
        environment:
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
        volumes:
            - ./data:/data
        command:
            - 'mongoimport --host mongo --port 27017 --db test --mode upsert --type json --file /data/account.json --jsonArray'
networks:
    myapp:

